"use client";

import { Avatar, AvatarFallback, AvatarImage } from "~/components/ui/avatar";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";
import { Skeleton } from "~/components/ui/skeleton";
import { useSession } from "~/features/auth/lib/auth-client";
import { cn } from "~/lib/utils";

export function ProfileTab() {
  const { data: session, isPending } = useSession();

  if (isPending) {
    return <ProfileTabSkeleton />;
  }

  return (
    <div className="flex h-full flex-col">
      <div className="border-b p-6">
        <h3 className="text-lg font-semibold">Profile</h3>
        <p className="text-muted-foreground text-sm">
          Manage your account details and personal information.
        </p>
      </div>

      <div className="flex-1 overflow-auto p-6">
        <div className="mx-auto max-w-xl space-y-6">
          {/* Avatar Section */}
          <div className="flex flex-col items-center gap-4">
            <Avatar className="size-20">
              <AvatarImage
                src={session?.user?.image || undefined}
                alt={session?.user?.name || "User"}
              />
              <AvatarFallback
                className={cn(`
                  from-primary/20 to-primary/5 ring-primary/20 bg-linear-to-br
                  text-lg ring-2
                `)}
              >
                {session?.user?.name?.slice(0, 2).toUpperCase() || "??"}
              </AvatarFallback>
            </Avatar>
            <div>
              <h2 className="text-xl font-medium">
                {session?.user?.name || "Unnamed User"}
              </h2>
              <p className="text-muted-foreground text-center text-sm">
                {session?.user?.email || "No email available"}
              </p>
            </div>
          </div>

          <Card className="gap-2 rounded pt-6">
            <CardHeader>
              <CardTitle className="text-base">What is this platform?</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm">This platform was built to save money. Instead of spending a flat rate on a monthly plan where most of the usage is low, you only pay for what you use. By paying for tokens instead of arbitrary messages, your costs are minimized.</p>
            </CardContent>
          </Card>

          <Card className="gap-2 rounded">
            <CardHeader>
              <CardTitle className="text-base">How are metrics calculated?</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm">
                <b>Tokens</b>
                {" "}
                are how language models measure the amount of text processed. The UI displays output tokens (tokens generated by the model) by default, but you can view the breakdown by hovering.
              </p>
              <p className="mt-2 text-sm">
                <b>Tokens per second</b>
                {" "}
                is calculated as the difference in tokens sent by the model, divided by the time elapsed. We calculate this server-side to ensure accuracy.
              </p>
              <p className="mt-2 text-sm">
                <b>TTFT</b>
                ,
                {" "}
                or Time To First Token, is the time it takes from when the message is sent to when the first token is received from the model.
              </p>
              <p className="mt-2 text-sm">
                <b>Cost (USD)</b>
                {" "}
                is calculated based on the pricing of the model used, multiplied by the total number of tokens processed. This is handled by the
                {" "}
                <a
                  href="http://tokenlens.dev/"
                  target="_blank"
                  rel="noreferrer"
                  className="underline"
                >
                  TokenLens
                </a>
                {" "}
                library, which provides fairly accurate cost tracking for various models. This is not 100% accurate, but should be fairly close to the actual cost incurred.
              </p>
            </CardContent>
          </Card>

          <Card className="gap-2 rounded">
            <CardHeader>
              <CardTitle className="text-base">What's on the roadmap?</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="list-disc space-y-1 pl-5 text-sm">
                <li>Analytics dashboard for usage tracking</li>
                <li>Forking, Handoff, and Thread Referencing</li>
                <li>Message editing and regenerating</li>
                <li>Public thread sharing</li>
              </ul>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}

function ProfileTabSkeleton() {
  return (
    <div className="flex h-full flex-col">
      <div className="border-b p-6">
        <Skeleton className="h-6 w-20" />
        <Skeleton className="mt-2 h-4 w-64" />
      </div>

      <div className="flex-1 overflow-auto p-6">
        <div className="mx-auto max-w-md space-y-6">
          <div className="flex flex-col items-center gap-4">
            <Skeleton className="size-20 rounded-full" />
            <Skeleton className="h-3 w-48" />
          </div>

          <div className="space-y-4">
            <div className="space-y-2">
              <Skeleton className="h-4 w-24" />
              <Skeleton className="h-9 w-full" />
            </div>

            <div className="space-y-2">
              <Skeleton className="h-4 w-16" />
              <Skeleton className="h-9 w-full" />
              <Skeleton className="h-3 w-72" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
